FROM python:latest

WORKDIR /app

# COPY requirements.txt /app
# RUN pip install -r requirements.txt
RUN pip install deepface flask flask_cors pyOpenSSL opencv-python-headless


COPY . /app

EXPOSE 5000
CMD ["python", "home.py"]


# sudo docker buildx build  --platform linux/amd64 -t simplyonline:face .

# docker run -p 5000:5000 -d simplyonline:face
