FROM python:3.10 

WORKDIR /app
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
COPY requirements.txt /app
RUN pip install -r requirements.txt
# RUN pip install deepface flask flask_cors pyOpenSSL opencv-python-headless


COPY . /app

# EXPOSE 5000
# CMD ["python", "home.py"]

# Install Gunicorn
RUN pip install gunicorn

COPY . /app

EXPOSE 5000
CMD ["gunicorn", "--config", "gunicorn_config.py", "home:app"]


# sudo docker buildx build  --platform linux/amd64 -t simplyonline:face .

# docker run -p 5000:5000 -d simplyonline:face



