FROM python:latest

WORKDIR /app

COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY . /app

EXPOSE 5000
CMD ["python", "home.py"]


# docker build -t simplyonline:face .

# docker run -p 5000:5000 -d simplyonline:face
